/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.AirlinerDirectory;
import Business.Customer;
import Business.CustomerDirectory;
import Business.FlightSchedule;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivibhatt
 */
public class CreateCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCustomerJPanel
     */
    private JPanel panel;
    private AirlinerDirectory airlineDirectory;
    private CustomerDirectory custDir;
    private Customer cust;
    private String gender;

    public CreateCustomerJPanel(JPanel panel, AirlinerDirectory airlineDirectory, CustomerDirectory custDir) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.custDir = custDir;
        this.gender = "";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bkCreateCustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        createFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        createLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        createEmailID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        createPassport = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCreateCustomer = new javax.swing.JButton();
        createGender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(174, 195, 195));
        setPreferredSize(new java.awt.Dimension(1040, 1020));

        bkCreateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-30.png"))); // NOI18N
        bkCreateCustomer.setText("Back");
        bkCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkCreateCustomerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create Customer");

        jLabel3.setText("First Name*");

        createFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFirstNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name*");

        createLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLastNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Email*");

        createEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmailIDActionPerformed(evt);
            }
        });

        jLabel6.setText("Passport # *");

        createPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPassportActionPerformed(evt);
            }
        });

        jLabel7.setText("Gender*");

        btnCreateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-user-male-60.png"))); // NOI18N
        btnCreateCustomer.setText("Create");
        btnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCustomerActionPerformed(evt);
            }
        });

        createGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- None --", "Male", "Female" }));
        createGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGenderActionPerformed(evt);
            }
        });

        jLabel9.setText("Status *");

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- None --", "Active", "Inactive" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bkCreateCustomer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(createFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(createLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createGender, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(btnCreateCustomer)))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bkCreateCustomer)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(createLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(createPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btnCreateCustomer)
                .addContainerGap(460, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bkCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkCreateCustomerActionPerformed
        // TODO add your handling code here:

        this.panel.remove(this);
        CardLayout layout = (CardLayout) this.panel.getLayout();
        Component[] comps = this.panel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageCustomerJPanel) {
                ManageCustomerJPanel rePopulateTable = (ManageCustomerJPanel) comp;
                rePopulateTable.populateManageCustomer();
            }
        }
        layout.previous(panel);
    }//GEN-LAST:event_bkCreateCustomerActionPerformed

    private void createFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createFirstNameActionPerformed

    private void createLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createLastNameActionPerformed

    private void createEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createEmailIDActionPerformed

    private void createPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPassportActionPerformed

    private void btnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustomerActionPerformed
        // TODO add your handling code here:
        
        if("".equals(createFirstName.getText())) {
            JOptionPane.showMessageDialog(null, "First Name Cannot be empty");            
        }else if("".equals(createLastName.getText())) {
            JOptionPane.showMessageDialog(null, "Last Name Cannot be empty");
        }else if("".equals(createEmailID.getText())) {
            JOptionPane.showMessageDialog(null, "Email ID Cannot be empty");
        }else if("".equals(createPassport.getText())) {
            JOptionPane.showMessageDialog(null, "Passport # Cannot be empty");
        }else if("-- None --".equals(createGender.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Please Select a Gender");
        }else if("-- None --".equals(statusCombo.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Customer status is mandatory");
        }else {
            Customer customer = new Customer();
            customer.setFirstName(createFirstName.getText());
            customer.setLastName(createLastName.getText());
            customer.setEmailId(createEmailID.getText());
            customer.setPassportNum(createPassport.getText());
            customer.setGender(createGender.getSelectedItem().toString());
            customer.setIsActive(statusCombo.getSelectedItem().toString() == "Active");
            custDir.addCustomer(customer);
            JOptionPane.showMessageDialog(null, "Customer Created Successfully");
            clearFields();
        }
        
        
        
        /*
       String firstName =createFirstName.getText();
   
        if (firstName.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "First Name Cannot be empty");
            return;
        } 
        //Last Name
        String lastName = createLastName.getText();
        if (lastName.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Last Name Cannot be empty");
            return;
        } else {
            lastName = createLastName.getText();
        }
        //Email 
        String email = createEmailID.getText();
     if (email.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Email ID Cannot be empty");
            return;
        } else {
            email = createEmailID.getText();
            
        }
        //Passport
        String passport = createPassport.getText();
        if (passport.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Passport # Cannot be empty");
            return;
        } else {
            passport = createPassport.getText();
            
        }
        
   
        if("--None--".equals(gender)){
             JOptionPane.showMessageDialog(null, "Please Select a Gender");
            return;
        }       
        else{
            gender = (String) createGender.getSelectedItem();  
        }
        Customer customer = new Customer();
        customer.setFirstName(firstName);
        customer.setLastName(lastName);
        customer.setEmailId(email);
        customer.setPassportNum(passport);
        customer.setGender(gender);
        
        //custDir.setCust(customer);
        custDir.addCustomer(customer);
        
        JOptionPane.showMessageDialog(null, "Customer Created Successfully");
        clearFields();
  */


    }//GEN-LAST:event_btnCreateCustomerActionPerformed

    private void clearFields() {

        createFirstName.setText("");
        createLastName.setText("");
        createEmailID.setText("");
        createPassport.setText("");
        createGender.setSelectedItem("-- None --");
        statusCombo.setSelectedItem("-- None --");
    }

    private void createGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGenderActionPerformed
        // TODO add your handling code here:

         //gender = (String) createGender.getSelectedItem();                                          

    }//GEN-LAST:event_createGenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkCreateCustomer;
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JTextField createEmailID;
    private javax.swing.JTextField createFirstName;
    private javax.swing.JComboBox<String> createGender;
    private javax.swing.JTextField createLastName;
    private javax.swing.JTextField createPassport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> statusCombo;
    // End of variables declaration//GEN-END:variables
}
