/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.AirlinerDirectory;
import Business.Airliner;
import Business.Airplane;
import Business.AirplaneDirectory;
import Business.MasterTravelSchedule;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mayank
 */
public class CreateAirliners extends javax.swing.JPanel {
    
    private JPanel panel;
    private AirlinerDirectory airlineDirectory;
    private MasterTravelSchedule masterTravelSchedule;
    private AirplaneDirectory airplaneDirectory;
    
    /**
     * Creates new form CreateAirliners
     */
    public CreateAirliners(JPanel panel, AirlinerDirectory airlineDirectory, AirplaneDirectory airplaneDirectory, MasterTravelSchedule masterTravelSchedule) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.airplaneDirectory = airplaneDirectory;
        this.masterTravelSchedule = masterTravelSchedule;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        airlinerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        airlinerFleetSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        airlinerHeadquarters = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bckCreateAirliner = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(174, 195, 195));
        setPreferredSize(new java.awt.Dimension(1040, 1020));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setText("Airliner Name *");

        jLabel2.setText("Fleet Size *");

        jLabel3.setText("Headquarter *");

        airlinerHeadquarters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerHeadquartersActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/travel (1).png"))); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Create Airliner");

        bckCreateAirliner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-30.png"))); // NOI18N
        bckCreateAirliner.setText("Back");
        bckCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckCreateAirlinerActionPerformed(evt);
            }
        });

        jLabel5.setText("Status *");

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- None --", "Active", "Inactive" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bckCreateAirliner))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(airlinerFleetSize)
                                    .addComponent(airlinerHeadquarters)
                                    .addComponent(airlinerName)
                                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jButton1)))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bckCreateAirliner)
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(airlinerFleetSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinerHeadquarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(557, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        boolean isAirlinerExist = false;
        
        if("".equals(airlinerName.getText())) {
            JOptionPane.showMessageDialog(null, "Airline Name is mandatory");
            
        }else if("".equals(airlinerHeadquarters.getText())) {
            JOptionPane.showMessageDialog(null, "Airline headquarters is mandatory");
            
        }else if("".equals(airlinerFleetSize.getText())) {
            JOptionPane.showMessageDialog(null, "Airline fleet size is mandatory");
            
        }else if("-- None --".equals(statusCombo.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Flight Schedule status is mandatory");
            
        }else {
            
            for(Airliner a : airlineDirectory.getAirlinerList()) {
                if(airlinerName.getText().equalsIgnoreCase(a.getAirlinerName())) {
                    isAirlinerExist = true;
                    JOptionPane.showMessageDialog(null, "Airliner with name \"" + a.getAirlinerName() + "\" already exist. Please enter a different name.");
                    break;
                }
            }
            
            if(isAirlinerExist == false) {
                
                int aFleet = 0;
                try {
                    aFleet = Integer.parseInt(airlinerFleetSize.getText());
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Please enter a valid fleet size");
                    return;
                }

                Airliner airliner = new Airliner();
                airliner.setAirlinerName(airlinerName.getText());
                airliner.setHeadquarter(airlinerHeadquarters.getText());
                airliner.setFleetSize(Integer.parseInt(airlinerFleetSize.getText()));
                airliner.setIsActive(statusCombo.getSelectedItem().toString() == "Active");
                airlineDirectory.addAirliner(airliner);
                clearFields();
                JOptionPane.showMessageDialog(null, "Airline Created Successfully"); 
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bckCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckCreateAirlinerActionPerformed
        // TODO add your handling code here:
//        AddAirline addAirline = new AddAirline(this.panel,  airlineDirectory,  airplaneDirectory,  masterTravelSchedule);
//        this.panel.add(addAirline, "AddAirline");
//        CardLayout layout = (CardLayout)this.panel.getLayout();
//        layout.next(panel);
//        this.panel.remove(this);
//        CardLayout layout = (CardLayout) this.panel.getLayout();
//        layout.previous(panel);
         this.panel.remove(this);
        CardLayout layout = (CardLayout)this.panel.getLayout();
        Component[] comps = this.panel.getComponents();
        for (Component comp : comps){
            if(comp instanceof AddAirline){
                AddAirline rePopulateTable = (AddAirline) comp;
                rePopulateTable.populateAirliners();
            }
        }
        layout.previous(panel);


    }//GEN-LAST:event_bckCreateAirlinerActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_formAncestorAdded

    private void airlinerHeadquartersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerHeadquartersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlinerHeadquartersActionPerformed
    
    public void clearFields() {
        airlinerName.setText("");
        airlinerHeadquarters.setText("");
        airlinerFleetSize.setText("");
        statusCombo.setSelectedItem("-- None --");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerFleetSize;
    private javax.swing.JTextField airlinerHeadquarters;
    private javax.swing.JTextField airlinerName;
    private javax.swing.JButton bckCreateAirliner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> statusCombo;
    // End of variables declaration//GEN-END:variables
}
