/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.AirlinerDirectory;
import Business.Airplane;
import Business.Customer;
import Business.CustomerDirectory;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivibhatt
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerJPanel
     */
    private JPanel panel;
    private AirlinerDirectory airlineDirectory;
    private CustomerDirectory custDir;
    private Customer cust;
    public ManageCustomerJPanel(JPanel panel, AirlinerDirectory airlineDirectory, CustomerDirectory custDir, Customer cust) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.custDir =custDir;
        this.cust = cust;
        populateManageCustomer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageCust = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();
        btnBackManageCust = new javax.swing.JButton();

        setBackground(new java.awt.Color(174, 195, 195));

        tblManageCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer #", "First Name", "Last Name", "Email ID", "Gender", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblManageCust.setRowHeight(25);
        tblManageCust.setRowMargin(3);
        jScrollPane1.setViewportView(tblManageCust);
        if (tblManageCust.getColumnModel().getColumnCount() > 0) {
            tblManageCust.getColumnModel().getColumn(0).setResizable(false);
            tblManageCust.getColumnModel().getColumn(1).setResizable(false);
            tblManageCust.getColumnModel().getColumn(2).setResizable(false);
            tblManageCust.getColumnModel().getColumn(3).setResizable(false);
            tblManageCust.getColumnModel().getColumn(4).setResizable(false);
            tblManageCust.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Customer");

        btnAddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-user-male-60.png"))); // NOI18N
        btnAddCustomer.setText(" Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnUpdateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-user-60.png"))); // NOI18N
        btnUpdateCustomer.setText("Update Customer");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        btnBackManageCust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-30.png"))); // NOI18N
        btnBackManageCust.setText("Back");
        btnBackManageCust.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnBackManageCustAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnBackManageCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackManageCustActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(346, 346, 346))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackManageCust))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(btnAddCustomer)
                        .addGap(86, 86, 86)
                        .addComponent(btnUpdateCustomer)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackManageCust)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateCustomer)
                    .addComponent(btnAddCustomer))
                .addContainerGap(482, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackManageCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackManageCustActionPerformed
        // TODO add your handling code here:
//        ManageTravelAgency manageTravelAgency = new ManageTravelAgency(this.panel, airlineDirectory);
//        this.panel.add(manageTravelAgency, "ManageTravelAgency");
//        CardLayout layout = (CardLayout)this.panel.getLayout();
//        layout.next(panel);
//        this.panel.remove(this);
//        CardLayout layout = (CardLayout) this.panel.getLayout();
//        layout.previous(panel);


        this.panel.remove(this);
        CardLayout layout = (CardLayout)this.panel.getLayout();
        Component[] comps = this.panel.getComponents();
        for (Component comp : comps){
            if(comp instanceof ManageTravelAgency){
                ManageTravelAgency rePopulateTable = (ManageTravelAgency) comp;
                //rePopulateTable.populate();
            }
        }
        layout.previous(panel);
    }//GEN-LAST:event_btnBackManageCustActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        CreateCustomerJPanel createCustomerJPanel = new CreateCustomerJPanel(this.panel, airlineDirectory, custDir);
        this.panel.add(createCustomerJPanel, "CreateCustomerJPanel");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblManageCust.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row to Update Details!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Customer customer = (Customer)tblManageCust.getValueAt(selectedRow, 0);
            
            UpdateCustomerJPanel updateCustomerJPanel = new UpdateCustomerJPanel(this.panel, airlineDirectory, custDir, customer);
            this.panel.add(updateCustomerJPanel, "UpdateCustomerJPanel");
            CardLayout layout = (CardLayout)this.panel.getLayout();
            layout.next(panel);
        }
    }//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnBackManageCustAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnBackManageCustAncestorAdded
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnBackManageCustAncestorAdded

public void populateManageCustomer() {
        DefaultTableModel dtm = (DefaultTableModel)tblManageCust.getModel();
        dtm.setRowCount(0);
        for(Customer cust : custDir.getCustomerList()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = cust;
            row[1] = cust.getFirstName();
            row[2] = cust.getLastName();
            row[3] = cust.getPassportNum();
            row[4] = cust.getGender(); 
            row[5] = cust.getIsActive()? "Active" : "Inactive";
            dtm.addRow(row);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnBackManageCust;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageCust;
    // End of variables declaration//GEN-END:variables
}
