/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.AirlinerDirectory;
import Business.AirplaneDirectory;
import Business.Customer;
import Business.CustomerDirectory;
import Business.MasterTravelSchedule;
import Business.Reservation;
import Business.ReservationDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivibhatt
 */
public class ManageBookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageBookingJPanel
     */
    private JPanel panel;
    private AirlinerDirectory airlineDirectory;
    private MasterTravelSchedule masterTravelSchedule;
    private CustomerDirectory custDir;
    private Customer cust;
    private ReservationDirectory reservationDirectory;
    private Reservation reservation;
    private AirplaneDirectory airplaneDirectory;
 
    public ManageBookingJPanel(JPanel panel, AirlinerDirectory airlineDirectory,AirplaneDirectory airplaneDirectory,MasterTravelSchedule masterTravelSchedule, CustomerDirectory custDir, Customer cust, ReservationDirectory reservationDirectory, Reservation reservation) {
        
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.masterTravelSchedule = masterTravelSchedule;
        this.custDir = custDir;
        this.cust = cust;
        this.reservationDirectory= reservationDirectory;
        this.reservation = reservation;
        this.airplaneDirectory =airplaneDirectory;
        initComponents();
        populateManageBooking();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bckBooking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageBooking = new javax.swing.JTable();
        btnViewBooking = new javax.swing.JButton();

        setBackground(new java.awt.Color(174, 195, 195));
        setPreferredSize(new java.awt.Dimension(1040, 1020));

        bckBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-30.png"))); // NOI18N
        bckBooking.setText("Back");
        bckBooking.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bckBookingAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        bckBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckBookingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Bookings");

        tblManageBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation ID", "Customer Name", "Flight Number", "Booking Status"
            }
        ));
        tblManageBooking.setRowHeight(25);
        tblManageBooking.setRowMargin(3);
        jScrollPane1.setViewportView(tblManageBooking);

        btnViewBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-airplane-take-off-60.png"))); // NOI18N
        btnViewBooking.setText("View Booking");
        btnViewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bckBooking))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 315, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(btnViewBooking)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bckBooking)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnViewBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bckBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckBookingActionPerformed
        // TODO add your handling code here:
//        ManageTravelAgency manageTravelAgency = new ManageTravelAgency( this.panel,  airlineDirectory, airplaneDirectory,  masterTravelSchedule,  custDir,  cust,  reservationDirectory,  reservation);
//        this.panel.add(manageTravelAgency, "ManageTravelAgency");
//        CardLayout layout = (CardLayout)this.panel.getLayout();
//        layout.next(panel);
//        this.panel.remove(this);
//        CardLayout layout = (CardLayout) this.panel.getLayout();
//        layout.previous(panel);

            
        this.panel.remove(this);
        CardLayout layout = (CardLayout)this.panel.getLayout();
        Component[] comps = this.panel.getComponents();
        for (Component comp : comps){
            if(comp instanceof ManageTravelAgency){
                ManageTravelAgency rePopulateTable = (ManageTravelAgency) comp;
                //rePopulateTable.populate();
            }
        }
        layout.previous(panel);
    }//GEN-LAST:event_bckBookingActionPerformed

    private void btnViewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookingActionPerformed
        // TODO add your handling code here:
        
          int selectedRow = tblManageBooking.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row to View Details!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Reservation reservation = (Reservation) tblManageBooking.getValueAt(selectedRow, 0);
            ViewBookingJPanel viewBookingJPanel = new ViewBookingJPanel(this.panel,  airlineDirectory,airplaneDirectory, masterTravelSchedule,  custDir,  cust,  reservationDirectory,  reservation);
            panel.add("ViewBookingJPanel", viewBookingJPanel);
            CardLayout layout = (CardLayout) panel.getLayout();
            layout.next(panel);

        }
//         ViewBookingJPanel viewBookingJPanel = new ViewBookingJPanel(this.panel, airlineDirectory, masterTravelSchedule,custDir,cust, reservation);
//        this.panel.add(viewBookingJPanel, "ViewBookingJPanel");
//        CardLayout layout = (CardLayout)this.panel.getLayout();
//        layout.next(panel);
    }//GEN-LAST:event_btnViewBookingActionPerformed

    private void bckBookingAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bckBookingAncestorAdded
        // TODO add your handling code here:
    
    }//GEN-LAST:event_bckBookingAncestorAdded
 public void populateManageBooking() {
        DefaultTableModel dtm = (DefaultTableModel)tblManageBooking.getModel();
        dtm.setRowCount(0);
        for(Reservation reservation :reservationDirectory.getReservationList() ){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = reservation;
            row[1] = reservation.getCustomer().getFirstName() + " " +reservation.getCustomer().getLastName();
            row[2] = reservation.getFlight().getFlightId();
            row[3] = reservation.isIsBooked() ? "Active" : "Cancelled";
            /*
             if(reservation.getSeat().getStatus().equalsIgnoreCase("Not Available")){
             row[3] = "Active";
            }else if(reservation.getSeat().getStatus().equalsIgnoreCase("Available")){
                 row[3] = "Cancelled";
             }
             */
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckBooking;
    private javax.swing.JButton btnViewBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageBooking;
    // End of variables declaration//GEN-END:variables
}
