/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.AirlinerDirectory;
import Business.Customer;
import Business.CustomerDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivibhatt
 */
public class UpdateCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCustomerJPanel
     */
    private JPanel panel;
    private AirlinerDirectory airlineDirectory;
    private CustomerDirectory custDir;
    private Customer cust;
    private String gender;
    
    public UpdateCustomerJPanel(JPanel panel, AirlinerDirectory airlineDirectory,CustomerDirectory custDir, Customer cust) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.custDir = custDir;
        this.cust = cust;
        displayUserDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
     private void displayUserDetails() {
         //Customer customer = new Customer();
         //System.out.println(custDir..getCust().getFirstName() + "GET ");
//        updateFirstName.setText(custDir.getCust().getFirstName() + "");
//        updateLastName.setText(custDir.getCust().getLastName() + "");
//        updateEmailID.setText(custDir.getCust().getEmailId() + "");
//        updatePassport.setText(custDir.getCust().getPassportNum()+ "");
//        updateGender.setSelectedItem(custDir.getCust().getGender() + "");
        
        updateFirstName.setText(cust.getFirstName()+ "");
        updateLastName.setText(cust.getLastName() + "");
        updateEmailID.setText(cust.getEmailId() + "");
        updatePassport.setText(cust.getPassportNum()+ "");
        updateGender.setSelectedItem(cust.getGender() + "");
        statusCombo.setSelectedItem(cust.getIsActive()? "Active" : "Inactive");
//        
  
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkUpdateCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUpdateCustomer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        updatePassport = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updateEmailID = new javax.swing.JTextField();
        updateLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        updateFirstName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        updateGender = new javax.swing.JComboBox<>();
        statusCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(174, 195, 195));

        bkUpdateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-30.png"))); // NOI18N
        bkUpdateCustomer.setText("Back");
        bkUpdateCustomer.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bkUpdateCustomerAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        bkUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkUpdateCustomerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Customer");

        btnUpdateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-user-60.png"))); // NOI18N
        btnUpdateCustomer.setText("UPDATE");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        jLabel7.setText("Status *");

        updatePassport.setEnabled(false);
        updatePassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePassportActionPerformed(evt);
            }
        });

        jLabel6.setText("Passport # *");

        jLabel5.setText("Email*");

        updateEmailID.setEnabled(false);
        updateEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmailIDActionPerformed(evt);
            }
        });

        updateLastName.setEnabled(false);
        updateLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLastNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name*");

        jLabel3.setText("First Name*");

        updateFirstName.setEnabled(false);
        updateFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFirstNameActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-save-60.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        updateGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- None --", "Male", "Female" }));
        updateGender.setEnabled(false);
        updateGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGenderActionPerformed(evt);
            }
        });

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- None --", "Active", "Inactive" }));

        jLabel8.setText("Gender*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bkUpdateCustomer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 333, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updatePassport, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(updateGender, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(statusCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(317, 317, 317))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(59, 59, 59)
                        .addComponent(btnUpdateCustomer)
                        .addGap(341, 341, 341))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(353, 353, 353))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bkUpdateCustomer)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(543, 543, 543))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatePassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePassportActionPerformed

    private void updateEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEmailIDActionPerformed

    private void updateLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateLastNameActionPerformed

    private void updateFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateFirstNameActionPerformed

    private void bkUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkUpdateCustomerActionPerformed
        // TODO add your handling code here:
//        ManageCustomerJPanel manageCustomerJPanel = new ManageCustomerJPanel(this.panel, airlineDirectory, custDir, cust);
//        this.panel.add(manageCustomerJPanel, "ManageCustomerJPanel");
//        CardLayout layout = (CardLayout)this.panel.getLayout();
//        layout.next(panel);
//         this.panel.remove(this);
//        CardLayout layout = (CardLayout) this.panel.getLayout();
//        layout.previous(panel);
this.panel.remove(this);
        CardLayout layout = (CardLayout)this.panel.getLayout();
        Component[] comps = this.panel.getComponents();
        for (Component comp : comps){
            if(comp instanceof ManageCustomerJPanel){
                ManageCustomerJPanel rePopulateTable = (ManageCustomerJPanel) comp;
                rePopulateTable.populateManageCustomer();
            }
        }
        layout.previous(panel);
    }//GEN-LAST:event_bkUpdateCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:
        
        setAllEnabled(true);
        btnSave.setEnabled(true);
        btnUpdateCustomer.setEnabled(false);
    }//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
        
        if("".equals(updateFirstName.getText())) {
            JOptionPane.showMessageDialog(null, "First Name Cannot be empty");            
        }else if("".equals(updateLastName.getText())) {
            JOptionPane.showMessageDialog(null, "Last Name Cannot be empty");
        }else if("".equals(updateEmailID.getText())) {
            JOptionPane.showMessageDialog(null, "Email ID Cannot be empty");
        }else if("".equals(updatePassport.getText())) {
            JOptionPane.showMessageDialog(null, "Passport # Cannot be empty");
        }else if("-- None --".equals(updateGender.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Please Select a Gender");
        }else if("-- None --".equals(statusCombo.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Customer status is mandatory");
        }else {
            cust.setFirstName(updateFirstName.getText());
            cust.setLastName(updateLastName.getText());
            cust.setEmailId(updateEmailID.getText());
            cust.setPassportNum(updatePassport.getText());
            cust.setGender(updateGender.getSelectedItem().toString());
            cust.setIsActive(statusCombo.getSelectedItem().toString() == "Active");
            btnSave.setEnabled(false);
            btnUpdateCustomer.setEnabled(true);
            setAllEnabled(false);
            JOptionPane.showMessageDialog(null, "Customer updated successfully");
        }
        
        
        /*
        String firstName =updateFirstName.getText();
   
        if (firstName.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "First Name Cannot be empty");
            return;
        } else {
            firstName = updateFirstName.getText();
        }
        //Last Name
        String lastName = updateLastName.getText();
        if (lastName.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Last Name Cannot be empty");
            return;
        } else {
            lastName = updateLastName.getText();
        }
        //Email 
        String email = updateEmailID.getText();
     if (email.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Email ID Cannot be empty");
            return;
        } else {
            email = updateEmailID.getText();
            
        }
        //Passport
        String passport = updatePassport.getText();
        if (passport.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Passport # Cannot be empty");
            return;
        } else {
            passport = updatePassport.getText();
            
        }
        
       
        if(gender.isEmpty() || "--None--".equals(gender)){
              JOptionPane.showMessageDialog(null, "Gender Cannot be empty");
            return;
        }
        
        //SetValues
       Customer customer = new Customer();
        customer.setFirstName(firstName);
        customer.setLastName(lastName);
        customer.setEmailId(email);
        customer.setPassportNum(passport);
        customer.setGender(gender);
        custDir.setCust(customer);
       // custDir.addCustomer(customer);
       
        
        btnSave.setEnabled(false);
        btnUpdateCustomer.setEnabled(true);

      
        */
    }//GEN-LAST:event_btnSaveActionPerformed

    private void updateGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGenderActionPerformed
        // TODO add your handling code here:
        //gender = (String) updateGender.getSelectedItem();   
    }//GEN-LAST:event_updateGenderActionPerformed

    private void bkUpdateCustomerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bkUpdateCustomerAncestorAdded
        // TODO add your handling code here:
   
    }//GEN-LAST:event_bkUpdateCustomerAncestorAdded

     private void setAllEnabled(boolean b) {
        updateFirstName.setEnabled(b);
        updateLastName.setEnabled(b);
        updateEmailID.setEnabled(b);
        updatePassport.setEnabled(b);
        updateGender.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkUpdateCustomer;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JTextField updateEmailID;
    private javax.swing.JTextField updateFirstName;
    private javax.swing.JComboBox<String> updateGender;
    private javax.swing.JTextField updateLastName;
    private javax.swing.JTextField updatePassport;
    // End of variables declaration//GEN-END:variables
}
