/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliner;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.FlightSchedule;
import Business.Airplane;
import Business.AirplaneDirectory;
import Business.Flight;
import Business.MasterTravelSchedule;
import Business.Reservation;
import Business.ReservationDirectory;
import Business.Seat;
import java.awt.CardLayout;
import java.awt.Component;
import static java.time.temporal.ChronoUnit.DAYS;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
/**
 *
 * @author Mayank
 */
public class UpdateFlight extends javax.swing.JPanel {
    
    private AirlinerDirectory airlineDirectory;
    private AirplaneDirectory airplaneDirectory;
    private JPanel panel;
    DefaultTableModel dtm;
    private Airliner airliner;
    private FlightSchedule selectedFlightSchedule;
    private Airplane selectedAirplane;
    private MasterTravelSchedule masterTravelSchedule;
    private Flight flight;
    private ReservationDirectory reservationDirectory;
    
    /**
     * Creates new form CreateFlight
     */
    public UpdateFlight(JPanel panel, AirlinerDirectory airlineDirectory, AirplaneDirectory airplaneDirectory, Airliner airliner, Flight flight, MasterTravelSchedule masterTravelSchedule, ReservationDirectory reservationDirectory) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.airplaneDirectory = airplaneDirectory;
        this.airliner = airliner;
        this.masterTravelSchedule = masterTravelSchedule;
        this.flight = flight;
        this.airliner = airliner;
        this.reservationDirectory = reservationDirectory;
        dtm = (DefaultTableModel) flightSeatsTbl.getModel();
        populateAirplanes();
        populateFlightSchedules();
        populateFlightDetails();
        //populateSeatDetails();
    }
    
    public void populateAirplanes() {
        int count = 0, index = 0;
        
        for(Airplane a : airliner.getAirplaneList()) {
            if(a.isIsActive()) {
                flightAirplaneCombo.addItem(a);
            }
            if(a == flight.getAirplane()) {
                index = count;
            }
            count++;
        }          
        flightAirplaneCombo.setSelectedIndex(index);
    }
    
    public void populateFlightSchedules() {
        int count = 0, index = 0;
        
        for(FlightSchedule s : airliner.getFlightScheduleList()) {
            if(s.isIsActive()) {
                flightScheduleCombo.addItem(s);
            }
            
            if(s == flight.getFlightSchedule()) {
                index = count;
            }
            count++;
        }
        flightScheduleCombo.setSelectedIndex(index);
    }
    
    public void populateFlightDetails() {
        flightNameTxt.setText(flight.getFlightName());
        if(flight.isIsActive()) {
            flightStatusCombo.setSelectedIndex(0);
        }else {
            flightStatusCombo.setSelectedIndex(1);
        }       
        
        //commenting dtm = (DefaultTableModel)flightSeatsTbl.getModel();
        //commenting dtm.setRowCount(0);
        
        /*Airplane a = (Airplane)flightAirplaneCombo.getSelectedItem();
        
        
        for(Seat s : flight.getFlightSeatList()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=s.getSeatName();
            row[1]=s.getPrice();
            row[2]=s.getType();
            row[3]=s.getStatus();
            dtm.addRow(row);
        }
        if((a.getSeatCol()*a.getSeatRow()) > flight.getFlightSeatList().size()) {
            dtm.setRowCount((a.getSeatCol()*a.getSeatRow())-flight.getFlightSeatList().size());
        }*/
        
    }
    
    public void populateSeatDetails() {
        Airplane a = (Airplane)flightAirplaneCombo.getSelectedItem();
        for(Seat s : flight.getFlightSeatList()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=s.getSeatName();
            row[1]=s.getPrice();
            row[2]=s.getType();
            row[3]=s.getStatus();
            dtm.addRow(row);
        }
        if((a.getSeatCol()*a.getSeatRow()) > flight.getFlightSeatList().size()) {
            dtm.setRowCount((a.getSeatCol()*a.getSeatRow())-flight.getFlightSeatList().size());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        flightNameTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        flightStatusCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        flightAirplaneCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightSeatsTbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        flightScheduleCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        sourceTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        departureDateTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        arrivalDateTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        arrivalTimeTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        departureTimeTxt = new javax.swing.JTextField();
        destiationTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        updateFlightBtn = new javax.swing.JButton();
        btnBackUpdateFlight = new javax.swing.JButton();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "Business" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));

        setBackground(new java.awt.Color(174, 195, 195));
        setPreferredSize(new java.awt.Dimension(1040, 1020));

        jPanel1.setBackground(new java.awt.Color(174, 195, 195));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight Details"));

        jLabel1.setText("Flight Name *");

        jLabel10.setText("Status *");

        flightStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Cancel" }));

        jLabel9.setText("Airplane *");

        flightAirplaneCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightAirplaneComboActionPerformed(evt);
            }
        });

        jLabel12.setText("Add Seats");

        flightSeatsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seat # *", "Price *", "Type *", "Status *"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        flightSeatsTbl.setRowHeight(25);
        flightSeatsTbl.setRowMargin(3);
        flightSeatsTbl.setSelectionBackground(new java.awt.Color(228, 228, 228));
        flightSeatsTbl.setSelectionForeground(new java.awt.Color(51, 51, 51));
        flightSeatsTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(flightSeatsTbl);
        if (flightSeatsTbl.getColumnModel().getColumnCount() > 0) {
            flightSeatsTbl.getColumnModel().getColumn(0).setResizable(false);
            flightSeatsTbl.getColumnModel().getColumn(1).setResizable(false);
            flightSeatsTbl.getColumnModel().getColumn(2).setResizable(false);
            flightSeatsTbl.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(jComboBox4));
            flightSeatsTbl.getColumnModel().getColumn(3).setResizable(false);
            flightSeatsTbl.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(jComboBox1));
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(flightAirplaneCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(flightStatusCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 214, Short.MAX_VALUE)
                            .addComponent(flightNameTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(flightNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(flightStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(flightAirplaneCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(174, 195, 195));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight Schedule Details"));

        jLabel11.setText("Select Flight Schedule to add to this Flight *");

        flightScheduleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightScheduleComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Source");

        sourceTxt.setEditable(false);

        jLabel3.setText("Destination");

        departureDateTxt.setEditable(false);

        jLabel4.setText("Arrival Date");

        arrivalDateTxt.setEditable(false);
        arrivalDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalDateTxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Arrival Time");

        arrivalTimeTxt.setEditable(false);

        jLabel7.setText("Destination Time");

        jLabel6.setText("Departure Date");

        departureTimeTxt.setEditable(false);
        departureTimeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureTimeTxtActionPerformed(evt);
            }
        });

        destiationTxt.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arrivalTimeTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sourceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(arrivalDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(192, 192, 192)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destiationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(departureDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(departureTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(flightScheduleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(flightScheduleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sourceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(destiationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(arrivalDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(departureDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(arrivalTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(departureTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel13.setText("Update a Flight");

        updateFlightBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-airplane-take-off-60.png"))); // NOI18N
        updateFlightBtn.setText("Update Flight");
        updateFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFlightBtnActionPerformed(evt);
            }
        });

        btnBackUpdateFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-30.png"))); // NOI18N
        btnBackUpdateFlight.setText("Back");
        btnBackUpdateFlight.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnBackUpdateFlightAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnBackUpdateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUpdateFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackUpdateFlight))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(updateFlightBtn)
                .addGap(445, 445, 445))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackUpdateFlight)
                .addGap(8, 8, 8)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(updateFlightBtn)
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void departureTimeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureTimeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureTimeTxtActionPerformed

    private void updateFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFlightBtnActionPerformed
        
        boolean isFlightExist = false;
        boolean seatCreated = false;
        //commenting dtm = (DefaultTableModel) flightSeatsTbl.getModel();
        int nRow = dtm.getRowCount();
        ArrayList<Seat> seatList = new ArrayList<>();        
        
        if("".equals(flightNameTxt.getText())) {
            JOptionPane.showMessageDialog(null, "Flight name is mandatory");
            
        }else if("-- None --".equals(flightStatusCombo.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Please select a status with respect to the flight");
            
        }else {  
            
            for(Flight f : masterTravelSchedule.getMasterFlightList()) {
                if(!(flight.getFlightName().equalsIgnoreCase(f.getFlightName()))) {
                    if(flightNameTxt.getText().equalsIgnoreCase(f.getFlightName())) {
                        isFlightExist = true;
                        JOptionPane.showMessageDialog(null, "Flight with name \"" + f.getFlightName() + "\" already exist. Please enter a different name.");
                        break;
                    }
                }
            }
            
            if(!isFlightExist) {
                
                for(Seat ss : flight.getFlightSeatList()) {
                    if(ss.getStatus().equals("Not Available")) {
                        
                    }
                }
                
                int count = 0;
                for(int i=0; i < nRow; i++) {
                    
                    if(i<flight.getFlightSeatList().size() && null != flight.getFlightSeatList().get(i) && !(flight.getFlightSeatList().get(i).getStatus().equals(flightSeatsTbl.getValueAt(i, 3)))) {
                        JOptionPane.showMessageDialog(null, "Seat Status cannot be changed at row" + (i+1) + " as this seat is already booked by a customer");
                        break;
                    }else if(null == flightSeatsTbl.getValueAt(i, 0) || "".equals(flightSeatsTbl.getValueAt(i, 0))) {
                        JOptionPane.showMessageDialog(null, "Please enter seat number at row " + (i+1));
                        break;
                    }else if(null == flightSeatsTbl.getValueAt(i, 1) || "".equals(flightSeatsTbl.getValueAt(i, 1))) {
                        JOptionPane.showMessageDialog(null, "Please enter price for the seat at row " + (i+1));
                        break;
                    }
                    else if(null == flightSeatsTbl.getValueAt(i, 2) || "".equals(flightSeatsTbl.getValueAt(i, 2))) {
                        JOptionPane.showMessageDialog(null, "Please select the seat type at row " + (i+1));
                        break;
                    }else if(null == flightSeatsTbl.getValueAt(i, 3) || "".equals(flightSeatsTbl.getValueAt(i, 3))) {
                        JOptionPane.showMessageDialog(null, "Please select the availability of seat at row " + (i+1));
                        break;
                    }else {
                        seatCreated = true;
                        count++;
                        Seat flightSeat = new Seat();
                        flightSeat.setSeatName(flightSeatsTbl.getValueAt(i, 0).toString());
                        flightSeat.setPrice((Double)flightSeatsTbl.getValueAt(i, 1));
                        flightSeat.setType(flightSeatsTbl.getValueAt(i, 2).toString());
                        flightSeat.setStatus(flightSeatsTbl.getValueAt(i, 3).toString());
                        seatList.add(flightSeat);
                    }                
                }
                if(!checkForAirplaneOverlap() && count == nRow) {
                    flight.setFlightName(flightNameTxt.getText());
                    flight.setIsActive((flightStatusCombo.getSelectedItem() == "Active"));
                    flight.setFlightSchedule(selectedFlightSchedule);
                    flight.setAirplane(selectedAirplane);    
                    flight.getFlightSeatList().clear();
                    flight.setFlightSeatList(seatList); 
                    for(Reservation r: reservationDirectory.getReservationList()) {
                        if(r.getFlight().getFlightId().equals(flight.getFlightId())) {
                            r.setIsBooked(false);
                            r.getSeat().setStatus("Available");
                        }
                    }

                    JOptionPane.showMessageDialog(null, "Flight is updated successfully");
                } 
            }
            
            
            
        }
        
        /*
        flight.setFlightName(flightNameTxt.getText());
        flight.setIsActive((flightStatusCombo.getSelectedItem() == "Active"));
        flight.setFlightSchedule(selectedFlightSchedule);
        flight.setAirplane(selectedAirplane);
        
        flight.getFlightSeatList().clear();
                
        ArrayList<Seat> seatList = new ArrayList<>();
        dtm = (DefaultTableModel) flightSeatsTbl.getModel();
        int nRow = dtm.getRowCount();
        for(int i=0; i < nRow; i++) {
            Seat flightSeat = new Seat();
            flightSeat.setSeatName(flightSeatsTbl.getValueAt(i, 0).toString());
            flightSeat.setPrice((Double)flightSeatsTbl.getValueAt(i, 1));
            flightSeat.setType(flightSeatsTbl.getValueAt(i, 2).toString());
            flightSeat.setStatus(flightSeatsTbl.getValueAt(i, 3).toString());
            seatList.add(flightSeat);
        }
        flight.setFlightSeatList(seatList);   
        */
        
    }//GEN-LAST:event_updateFlightBtnActionPerformed

    private boolean checkForAirplaneOverlap() {
        
        boolean isOverlap = false;
        Flight oldF = new Flight();
        
        for(Flight f : airliner.getFlightList()) {
            if(f.getAirplane() == selectedAirplane && f != flight) {                
                if(selectedFlightSchedule.getDepartureDate().isBefore(f.getFlightSchedule().getArrivalDate()) &&
                   f.getFlightSchedule().getDepartureDate().isBefore(selectedFlightSchedule.getArrivalDate())) {
                    isOverlap = true;
                    oldF = f;
                }else if((f.getFlightSchedule().getArrivalDate().equals(selectedFlightSchedule.getArrivalDate()) && 
                          f.getFlightSchedule().getDepartureDate().equals(selectedFlightSchedule.getDepartureDate())) ||
                        f.getFlightSchedule().getArrivalDate().equals(selectedFlightSchedule.getDepartureDate()) ||
                        f.getFlightSchedule().getDepartureDate().equals(selectedFlightSchedule.getArrivalDate())
                        ){                    
                    long diff1 = DAYS.between(selectedFlightSchedule.getDepartureDate(), selectedFlightSchedule.getArrivalDate());
                    long diff2 = DAYS.between(f.getFlightSchedule().getDepartureDate(), f.getFlightSchedule().getArrivalDate());
                    
                    if(diff2 > diff1) {
                        if(selectedFlightSchedule.getArrivalTime().isAfter(f.getFlightSchedule().getDepartureTime())) {
                            isOverlap = true;
                            oldF = f;
                        }
                    }
                    if(diff1 > diff2) {
                        if(f.getFlightSchedule().getArrivalTime().isAfter(selectedFlightSchedule.getDepartureTime())) {
                            isOverlap = true;
                            oldF = f;
                        }
                    }
                    if(diff1 == diff2) {
                        if(selectedFlightSchedule.getDepartureTime().isBefore(f.getFlightSchedule().getArrivalTime()) &&
                            f.getFlightSchedule().getDepartureTime().isBefore(selectedFlightSchedule.getArrivalTime())) {
                             isOverlap = true;
                             oldF = f;
                         }
                    }
                }
            }
        }
        
        if(isOverlap == true) {
            JOptionPane.showMessageDialog(null, "This airplane is already assigned on Flight " + oldF.getFlightName() + ". Please select a different airplane or modify the flght schedule");
        }
        
        return isOverlap;        
    }
    
    private void flightAirplaneComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightAirplaneComboActionPerformed
        
        /*selectedAirplane = (Airplane)flightAirplaneCombo.getSelectedItem();
        int totalSeats = (selectedAirplane.getSeatCol() * selectedAirplane.getSeatRow());
        dtm.setRowCount(totalSeats);
        if(selectedAirplane == flight.getAirplane()) {
            //commenting dtm = (DefaultTableModel)flightSeatsTbl.getModel();           
            for(Seat s : flight.getFlightSeatList()){
                Object[] row = new Object[dtm.getColumnCount()];
                row[0]=s.getSeatName();
                row[1]=s.getPrice();
                row[2]=s.getType();
                row[3]=s.getStatus();
                dtm.addRow(row);
            }
            
            if((selectedAirplane.getSeatCol()*selectedAirplane.getSeatRow()) > flight.getFlightSeatList().size()) {
                dtm.setRowCount((selectedAirplane.getSeatCol()*selectedAirplane.getSeatRow())-flight.getFlightSeatList().size());
            }
        }  
        */    
        
        selectedAirplane = (Airplane)flightAirplaneCombo.getSelectedItem();
        dtm.setRowCount(0);
        //if(selectedAirplane == flight.getAirplane()) {
            dtm = (DefaultTableModel)flightSeatsTbl.getModel();           
            for(Seat s : flight.getFlightSeatList()){
                Object[] row = new Object[dtm.getColumnCount()];
                row[0]=s.getSeatName();
                row[1]=s.getPrice();
                row[2]=s.getType();
                row[3]=s.getStatus();
                dtm.addRow(row);
            } 
            System.out.println("!!!!!!! " + selectedAirplane.getSeatCol());
            System.out.println("!!!!!!! " + selectedAirplane.getSeatRow());
            System.out.println("!!!!!!! " + flight.getFlightSeatList().size());
            
            if((selectedAirplane.getSeatCol()*selectedAirplane.getSeatRow()) > flight.getFlightSeatList().size()) {
                System.out.println("inside()()()()");
                dtm.setRowCount((selectedAirplane.getSeatCol()*selectedAirplane.getSeatRow()));
            }
        //}else {
            if(selectedAirplane != flight.getAirplane()) {
                int totalSeats = (selectedAirplane.getSeatCol() * selectedAirplane.getSeatRow());
                dtm.setRowCount(totalSeats);
            }
        //}
        
    }//GEN-LAST:event_flightAirplaneComboActionPerformed

    private void flightScheduleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightScheduleComboActionPerformed
        selectedFlightSchedule = (FlightSchedule)flightScheduleCombo.getSelectedItem();
        
        sourceTxt.setText(selectedFlightSchedule.getSource());
        destiationTxt.setText(selectedFlightSchedule.getDestination());
        arrivalDateTxt.setText((selectedFlightSchedule.getArrivalDate()).toString());
        arrivalTimeTxt.setText((selectedFlightSchedule.getArrivalTime()).toString());
        departureDateTxt.setText((selectedFlightSchedule.getDepartureDate()).toString());
        departureTimeTxt.setText((selectedFlightSchedule.getDepartureTime()).toString());   
    }//GEN-LAST:event_flightScheduleComboActionPerformed

    private void arrivalDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalDateTxtActionPerformed
        
    }//GEN-LAST:event_arrivalDateTxtActionPerformed

    private void btnBackUpdateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUpdateFlightActionPerformed
        // TODO add your handling code here:
//        AirlinerFunction airLinerFunction = new AirlinerFunction(this.panel,  airlineDirectory,  airplaneDirectory,  airliner,  masterTravelSchedule);
//        this.panel.add(airLinerFunction, "AirlinerFunction");
//        CardLayout layout = (CardLayout)this.panel.getLayout();
//        layout.next(panel);
//        this.panel.remove(this);
//        CardLayout layout = (CardLayout) this.panel.getLayout();
//        layout.previous(panel);
     this.panel.remove(this);
        CardLayout layout = (CardLayout)this.panel.getLayout();
        Component[] comps = this.panel.getComponents();
        for (Component comp : comps){
            if(comp instanceof AirlinerFunction){
                AirlinerFunction rePopulateTable = (AirlinerFunction) comp;
                rePopulateTable.populateAirlineFlights();
            }
        }
        layout.previous(panel);

    }//GEN-LAST:event_btnBackUpdateFlightActionPerformed

    private void btnBackUpdateFlightAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnBackUpdateFlightAncestorAdded
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnBackUpdateFlightAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalDateTxt;
    private javax.swing.JTextField arrivalTimeTxt;
    private javax.swing.JButton btnBackUpdateFlight;
    private javax.swing.JTextField departureDateTxt;
    private javax.swing.JTextField departureTimeTxt;
    private javax.swing.JTextField destiationTxt;
    private javax.swing.JComboBox<Airplane> flightAirplaneCombo;
    private javax.swing.JTextField flightNameTxt;
    private javax.swing.JComboBox<FlightSchedule> flightScheduleCombo;
    private javax.swing.JTable flightSeatsTbl;
    private javax.swing.JComboBox<String> flightStatusCombo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sourceTxt;
    private javax.swing.JButton updateFlightBtn;
    // End of variables declaration//GEN-END:variables
}
